#!/usr/bin/env python
# coding=utf-8

import sys
import os
import time
import subprocess
import re
from distutils.spawn import find_executable

# Py2/3 compatibility
# Python3 renamed raw_input to input
try:
    input = raw_input
except NameError:
    pass

try:
    reload

except NameError:
    from importlib import reload

# check where we are and load default directory
if os.path.isdir("/usr/share/setoolkit"):
    if not os.path.isfile("setoolkit"):
        os.chdir("/usr/share/setoolkit")
        sys.path.append("/usr/share/setoolkit")

import src.core.setcore as core

# if we can't see our config then something didn't go good..
if not os.path.isfile("/etc/setoolkit/set.config"):
    core.print_error("Cannot locate SET executable. Try running from the local directory.")
    core.print_error("If this does not work, please run the setup.py install file.")
    sys.exit()


#
# Simple client mode for SET
#
#
# try to import pexpect
try:
    import pexpect

# if pexpect fails
except ImportError:
    print("\n[*] PEXPECT требуется, пожалуйста, скачайте и установите перед запуском этого...")
    print("[*] Выход из режима SEAUTOMATE...")
    sys.exit()

# try to define filename through argument specified during command line mode
try:
    filename = sys.argv[1]

# if we through an exception spit out the command line syntax
except IndexError:
    print("\nSocial-Engineer Toolkit Automate - Автоматизация для SET ")
    print("\nПросто создайте файл, у которого есть каждая опция, которую вы хотите из режима меню.")
    print("Например, ваш файл должен выглядеть примерно так:")
    print("\n2\n2\n2\nhttps://gmail.com\n2\n2\n443\netc.\n")
    print("Usage: ./seautomate <filename>")
    sys.exit()

# if the filename doesnt exist, throw an error
if not os.path.isfile(filename):
    print("\n[*] К сожалению, не удалось найти это имя файла, попробуйте еще раз.\n")
    sys.exit()

password = False
# if the path is around
if os.path.isfile(filename):
    try:
        print("[*] Нерест SET в поточном процессе...")
        cmd = find_executable('python3') or find_executable('python')
        child = pexpect.spawn("{} setoolkit".format(cmd))
        child.expect("99\) Выход из инструментария социального инженера")
        with open(filename) as fileopen:
            for line in fileopen:
                line = line.rstrip()
                # if we just use enter send default
                if line == "":
                    line = "blank line"

                #match1 = re.search("OMGPASSWORDHERE", line)
                #if match1:
                #    line = line.replace("OMGPASSWORDHERE", "")
                #    password = True

                #if password is False:
                print("[*] Отправка команды {0} в интерфейс..".format(line))
                #if password is True:
                #    print("[*] Sending command [**********] (password masked) to the interface...")
                #    password = False

                if line == "blank line":
                    line = "\n"

                if line == "CONTROL-C-HERE":
                    try:
                        print("[*] Это может занять несколько секунд, пока SET догоняет...")
                        child.expect("Следующая строка тела:")
                        time.sleep(2)
                        child.sendline("\n")
                        child.sendcontrol('c')

                    # if the user is using pexpect < 2.3
                    except AttributeError:
                        print("[-] Error: Вы используете pexpect <2.3, который необходим для этой функции")
                        choice = input("Вы хотите установить его сейчас да или нет: ")
                        if choice == "yes" or choice == "y":
                            #subprocess.Popen("wget http://sourceforge.net/projects/pexpect/files/pexpect/Release%202.3/pexpect-2.3.tar.gz;"
                            #                 "tar -zxvf pexpect-2.3.tar.gz;"
                            #                 "cd pexpect-2.3;"
                            #                 "python setup.py install;"
                            #                 "cd ..;"
                            #                 "rm -rf pexpect-2*", shell=True).wait()
                            subprocess.Popen("pip install pexpect", shell=True).wait()
                            try:
                                reload(pexpect)
                                child.sendcontrol('c')
                            except:
                                print("[*] Перезапустите Social-Engineer Toolkit для внесения изменений.")
                                sys.exit()
                if line != "CONTROL-C-HERE":
                    child.sendline(line)

        print("[*] Закончена отправка команд, взаимодействующих с интерфейсом..")
        child.interact()

    # sometimes pexpect can throw errors upon exit this handles them
    except OSError:
        sys.exit()

    # handle keyboardinterrupts (controlc)
    except KeyboardInterrupt:
        print("[*] Обнаружен Control-C, выход из Social-Engineer Toolkit..")
        sys.exit()

    # handle everything else
    except Exception as e:
        print("[*] Что-то пошло не так, ошибка печати: {0}".format(e))
