#!/usr/bin/python

#
# Simple proxy for SET, note will show up in history
#

import sys
import getpass
import os
import subprocess
import re

import src.core.setcore as core

# Py2/3 compatibility
# Python3 renamed raw_input to input
try:
    input = raw_input
except NameError:
    pass

# grab the operating system
operating_system = core.check_os()

# if windows then do some stuff
if operating_system == "posix":

    definepath = os.getcwd()

    print("\n[*]Добро пожаловать в утилиту настройки SET-Proxy")
    print("\nВведите информацию о настройке прокси ниже.\n\nExample: http://10.3.1.1:8080\n")

    try:

        proxy = input("Введите прокси-сервер: ")
        username = input("Введите имя пользователя для прокси (нажмите Enter, если нет): ")
        password = getpass.getpass("Введите пароль для прокси (нажмите Enter, чтобы ничего не было): ")

    except KeyboardInterrupt:
        print("\n[!]Выход из инструментария социального инженера.")
        sys.exit()

    if username != "":
        proxy_string = "export http_proxy='http://{0}:{1}@{2}'".format(username, password, proxy)
    else:
        proxy_string = "export http_proxy='http://{0}'".format(proxy)

    with open(os.path.join(core.userconfigpath, "proxy.config"), "w") as filewrite:
        filewrite.write(proxy_string)

    def kill_proc(port, flag):
        proc = subprocess.Popen("netstat -antp | grep '{0}'".format(port), shell=True, stdout=subprocess.PIPE)
        stdout_value = proc.communicate()[0]
        a = re.search("\d+/{0}".format(flag), stdout_value)
        if a:
            b = a.group()
            b = b.replace("/{0}".format(flag), "")
            subprocess.Popen("kill -9 {0} 1> /dev/null 2> /dev/null".format(b), shell=True).wait()

    # cleans up stale processes from SET
    try:
        # kill anything python running on 80
        kill_proc("80", "python")
        # kill anything on 443 ruby which is generally a rogue listener
        kill_proc("443", "ruby")

    # handle errors
    except Exception as error:
        core.log(error)

else:
    print("[!] К сожалению, это работает только в системах на основе posix (nix) и не совместимо с этой операционной системой.")
