#!/usr/bin/env python
# coding=utf-8
#
# simple git update for set pulling from core modules
#
import os
import sys



# check where we are and load default directory
if os.path.isdir("/usr/share/setoolkit"):
    if not os.path.isfile("se-toolkit"):
        os.chdir("/usr/share/setoolkit")
        sys.path.append("/usr/share/setoolkit")

import src.core.setcore as core

# if we can't see our config then something didn't go good..
if not os.path.isfile("/etc/setoolkit/set.config"):
    core.print_error("Не удается найти исполняемый файл SET. Попробуйте запустить из локального каталога.")
    core.print_error("Если это не работает, пожалуйста, запустите установочный файл setup.py.")
    sys.exit()

try:
    # pull update set from the core libraries
    core.update_set()

# except keyboard interrupts
except KeyboardInterrupt:
    print("\n[!] Control-C обнаружен. Выход из обновления SET.")

# handle all other errors
except Exception as e:
    print("\n[!] Что-то пошло не так .. Распечатка ошибки: {0}".format(e))
